---
Title: Jack Murray - Personal Portfolio
Header: |
  # Jack Murray
  Full-Stack Software Engineer
Footer: |
  &copy; 2024 Jack Murray. All rights reserved.
  <script async defer src="https://scripts.simpleanalyticscdn.com/latest.js"></script>
  <noscript><img src="https://queue.simpleanalyticscdn.com/noscript.gif" alt="" referrerpolicy="no-referrer-when-downgrade" /></noscript>
